# CUDA 12.x only supports GCC up to 13 as nvcc's host compiler. On HPC clusters the
# main CXX compiler may be older while `gcc` on PATH (used by nvcc by default) is GCC 14+.
#
# Include once before project() and once after project(), before find_package(Torch)
# or find_package(metatensor_torch) enable CUDA.
#
# Override detection with METATOMIC_CUDA_HOST_COMPILER or CUDAHOSTCXX.

function(_metatomic_gcc_major_version _compiler _out_major)
    execute_process(
        COMMAND "${_compiler}" -dumpversion
        OUTPUT_VARIABLE _version
        OUTPUT_STRIP_TRAILING_WHITESPACE
        ERROR_QUIET
        RESULT_VARIABLE _result
    )
    if(NOT _result EQUAL 0)
        set(${_out_major} -1 PARENT_SCOPE)
        return()
    endif()
    if(_version MATCHES "^([0-9]+)")
        set(${_out_major} ${CMAKE_MATCH_1} PARENT_SCOPE)
    else()
        set(${_out_major} -1 PARENT_SCOPE)
    endif()
endfunction()

function(_metatomic_try_cuda_host_compiler _compiler _out_var)
    if(NOT EXISTS "${_compiler}")
        return()
    endif()
    _metatomic_gcc_major_version("${_compiler}" _major)
    if(_major GREATER 0 AND _major LESS_EQUAL 13)
        set(${_out_var} "${_compiler}" PARENT_SCOPE)
    endif()
endfunction()

function(_metatomic_apply_cuda_host_compiler _cuda_host _reason)
    get_filename_component(_cuda_host "${_cuda_host}" REALPATH)
    set(CMAKE_CUDA_HOST_COMPILER "${_cuda_host}" CACHE FILEPATH "CUDA host compiler" FORCE)
    message(STATUS "${_reason}; using ${_cuda_host} as CMAKE_CUDA_HOST_COMPILER for nvcc")
endfunction()

function(_metatomic_find_cuda_host_compiler _out_var)
    set(_explicit "")
    if(DEFINED ENV{METATOMIC_CUDA_HOST_COMPILER} AND NOT "$ENV{METATOMIC_CUDA_HOST_COMPILER}" STREQUAL "")
        set(_explicit "$ENV{METATOMIC_CUDA_HOST_COMPILER}")
    elseif(DEFINED ENV{CUDAHOSTCXX} AND NOT "$ENV{CUDAHOSTCXX}" STREQUAL "")
        set(_explicit "$ENV{CUDAHOSTCXX}")
    endif()
    if(_explicit)
        _metatomic_try_cuda_host_compiler("${_explicit}" _found)
        if(_found)
            set(${_out_var} "${_found}" PARENT_SCOPE)
            return()
        endif()
        message(WARNING "Explicit CUDA host compiler '${_explicit}' is missing or uses GCC > 13")
    endif()

    if(CMAKE_CUDA_HOST_COMPILER)
        _metatomic_try_cuda_host_compiler("${CMAKE_CUDA_HOST_COMPILER}" _found)
        if(_found)
            set(${_out_var} "${_found}" PARENT_SCOPE)
            return()
        endif()
    endif()

    if(DEFINED ENV{CONDA_PREFIX})
        foreach(_candidate IN ITEMS
            "$ENV{CONDA_PREFIX}/bin/x86_64-conda-linux-gnu-g++"
            "$ENV{CONDA_PREFIX}/bin/x86_64-conda-linux-gnu-gcc"
        )
            _metatomic_try_cuda_host_compiler("${_candidate}" _found)
            if(_found)
                set(${_out_var} "${_found}" PARENT_SCOPE)
                return()
            endif()
        endforeach()
    endif()

    foreach(_name IN ITEMS g++-13 gcc-13 g++-12 gcc-12 g++-11 gcc-11)
        find_program(_candidate NAMES ${_name})
        if(_candidate)
            _metatomic_try_cuda_host_compiler("${_candidate}" _found)
            if(_found)
                set(${_out_var} "${_found}" PARENT_SCOPE)
                return()
            endif()
        endif()
    endforeach()

    file(GLOB _opt_gcc_dirs /opt/gcc-13* /opt/gcc-12* /opt/gcc-11*)
    list(SORT _opt_gcc_dirs COMPARE NATURAL ORDER DESCENDING)
    foreach(_gcc_dir IN LISTS _opt_gcc_dirs)
        foreach(_candidate IN ITEMS "${_gcc_dir}/build/bin/g++" "${_gcc_dir}/bin/g++")
            _metatomic_try_cuda_host_compiler("${_candidate}" _found)
            if(_found)
                set(${_out_var} "${_found}" PARENT_SCOPE)
                return()
            endif()
        endforeach()
    endforeach()

    foreach(_candidate IN ITEMS /usr/bin/g++-13 /usr/bin/g++-12 /usr/bin/g++-11)
        _metatomic_try_cuda_host_compiler("${_candidate}" _found)
        if(_found)
            set(${_out_var} "${_found}" PARENT_SCOPE)
            return()
        endif()
    endforeach()
endfunction()

function(_metatomic_compiler_needs_cuda_host_override _compiler _out_var)
    set(${_out_var} FALSE PARENT_SCOPE)
    if(NOT _compiler)
        return()
    endif()
    _metatomic_gcc_major_version("${_compiler}" _major)
    if(_major GREATER 13)
        set(${_out_var} TRUE PARENT_SCOPE)
    endif()
endfunction()

function(metatomic_configure_cuda_host_compiler)
    if(DEFINED ENV{METATOMIC_CUDA_HOST_COMPILER} AND NOT "$ENV{METATOMIC_CUDA_HOST_COMPILER}" STREQUAL "")
        _metatomic_try_cuda_host_compiler("$ENV{METATOMIC_CUDA_HOST_COMPILER}" _cuda_host)
        if(_cuda_host)
            _metatomic_apply_cuda_host_compiler("${_cuda_host}" "METATOMIC_CUDA_HOST_COMPILER is set")
            return()
        endif()
        message(WARNING "METATOMIC_CUDA_HOST_COMPILER='$ENV{METATOMIC_CUDA_HOST_COMPILER}' is missing or uses GCC > 13")
    endif()

    if(DEFINED ENV{CUDAHOSTCXX} AND NOT "$ENV{CUDAHOSTCXX}" STREQUAL "")
        _metatomic_try_cuda_host_compiler("$ENV{CUDAHOSTCXX}" _cuda_host)
        if(_cuda_host)
            _metatomic_apply_cuda_host_compiler("${_cuda_host}" "CUDAHOSTCXX is set")
            return()
        endif()
        message(WARNING "CUDAHOSTCXX='$ENV{CUDAHOSTCXX}' is missing or uses GCC > 13")
    endif()

    if(CMAKE_CUDA_HOST_COMPILER)
        _metatomic_gcc_major_version("${CMAKE_CUDA_HOST_COMPILER}" _cuda_host_major)
        if(_cuda_host_major GREATER 0 AND _cuda_host_major LESS_EQUAL 13)
            return()
        endif()
    endif()

    set(_need_override FALSE)
    set(_reason "")

    if(CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
        string(REGEX MATCH "^([0-9]+)" _cxx_major "${CMAKE_CXX_COMPILER_VERSION}")
        if(_cxx_major GREATER 13)
            set(_need_override TRUE)
            set(_reason "Main CXX compiler ${CMAKE_CXX_COMPILER} is GCC ${_cxx_major}")
        endif()
    elseif(DEFINED ENV{CXX} AND NOT "$ENV{CXX}" STREQUAL "")
        _metatomic_compiler_needs_cuda_host_override("$ENV{CXX}" _needs)
        if(_needs)
            set(_need_override TRUE)
            set(_reason "CXX environment variable points to $ENV{CXX}")
        endif()
    endif()

    find_program(_metatomic_default_gcc gcc)
    if(_metatomic_default_gcc)
        _metatomic_compiler_needs_cuda_host_override("${_metatomic_default_gcc}" _needs)
        if(_needs)
            set(_need_override TRUE)
            if(_reason STREQUAL "")
                set(_reason "Default gcc on PATH (${_metatomic_default_gcc})")
            else()
                set(_reason "${_reason} and default gcc on PATH (${_metatomic_default_gcc})")
            endif()
        endif()
    endif()

    if(NOT _need_override)
        return()
    endif()

    _metatomic_find_cuda_host_compiler(_cuda_host)
    if(_cuda_host)
        _metatomic_apply_cuda_host_compiler("${_cuda_host}" "${_reason}")
    else()
        message(FATAL_ERROR
            "${_reason}, which cannot be used as nvcc's host compiler with CUDA 12.x.\n"
            "Set METATOMIC_CUDA_HOST_COMPILER or CUDAHOSTCXX to a GCC 13 (or older) compiler, "
            "for example the conda env g++: export METATOMIC_CUDA_HOST_COMPILER=\$CONDA_PREFIX/bin/x86_64-conda-linux-gnu-g++")
    endif()
endfunction()

if(NOT _metatomic_cuda_host_compiler_checked OR CMAKE_CXX_COMPILER_ID)
    if(NOT _metatomic_cuda_host_compiler_checked)
        set(_metatomic_cuda_host_compiler_checked TRUE)
    endif()
    metatomic_configure_cuda_host_compiler()
endif()
